services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: queue
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
  redis:
    image: redis:8.0.1-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  rabbitmq:
